In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn.preprocessing as spre

# Standardization Scaling

In [2]:
a1 = np.array([-70,-100,0,100,200.0]).reshape(-1,1)


In [3]:
s = spre.StandardScaler()
#s = spre.StandardScaler(with_mean=True,with_std=False)

In [4]:
s.fit(a1)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [5]:
s.transform(a1)

array([[-0.86546214],
       [-1.13591905],
       [-0.23439599],
       [ 0.66712706],
       [ 1.56865012]])

In [6]:
s.fit_transform(a1)

array([[-0.86546214],
       [-1.13591905],
       [-0.23439599],
       [ 0.66712706],
       [ 1.56865012]])

# Normalization Scaling (min-max)

In [7]:
a1 = np.array([30.0,40,70,120]).reshape(-1,1)
s = spre.MinMaxScaler()

In [8]:
a2 = s.fit_transform(a1)

In [9]:
a2

array([[0.        ],
       [0.11111111],
       [0.44444444],
       [1.        ]])

In [10]:
s = spre.MinMaxScaler((30,120))

In [11]:
s.fit_transform(a2)

array([[ 30.],
       [ 40.],
       [ 70.],
       [120.]])

# Robust Scaling

In [12]:
s = spre.RobustScaler()

In [13]:
s.fit_transform(a1)

array([[-0.55555556],
       [-0.33333333],
       [ 0.33333333],
       [ 1.44444444]])

In [14]:
Q1 = np.percentile(a1,25)
Q1

37.5

In [15]:
Q2 =np.percentile(a1,50)
Q2

55.0

In [16]:
Q3 = np.percentile(a1,75)
Q3

82.5

In [17]:
for i in range(len(a1)):
    a1[i,0]= ((a1[i,0] - Q2) / (Q3 - Q1))


In [18]:
a1

array([[-0.55555556],
       [-0.33333333],
       [ 0.33333333],
       [ 1.44444444]])